# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tigerline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tigerline.State'),
            preserve_default=False,
        ),
    ]
